name: Build and push docker image to Github Container Registry
on:
  push:
    branches: [ '**' ]

jobs:
  build-and-push-docker-image:
    name: Build and push Docker image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
          include-prerelease: true

      - uses: actions/checkout@v2
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Add GGroupp NuGet Source
        run: dotnet nuget add source ${{ secrets.GGROUPP_NUGET_SOURCE_URL }} -n ggroupp -u ${{ secrets.GGROUPP_NUGET_SOURCE_USER_NAME }} -p ${{ secrets.GGROUPP_NUGET_SOURCE_USER_PASSWORD }} --store-password-in-clear-text

      - name: Publish Application.csproj
        run: dotnet publish ./src/*/Application.csproj -c Release -o './docker/publish'

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GGROUPP_GITHUB_CONTAINER_REGISTRY_USER }}
          password: ${{ secrets.GGROUPP_GITHUB_CONTAINER_REGISTRY_TOKEN }}
      
      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: ./docker
          tags: |
            ghcr.io/ggrouppfoundation/internal-support-bot-app-image:v1
            ghcr.io/ggrouppfoundation/internal-support-bot-app-image:latest
          push: true

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}