name: Deploy Bot App to Test

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub Action
      uses: actions/checkout@v4

    - name: Get version
      id: get_version
      run: echo "version=$(echo $GITHUB_REF | cut -d / -f 3)" >> $GITHUB_OUTPUT

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_ARTIFACT }}

    - name: Ensure Publish Directory Exists
      run: mkdir -p ./publish

    - name: Download from Blob Storage
      run: |
        az storage blob download \
          --name ${{ vars.AZURE_ARTIFACT_NAME }}-${{ steps.get_version.outputs.version }}.zip \
          --file ./publish/${{ vars.AZURE_ARTIFACT_NAME }}-${{ steps.get_version.outputs.version }}.zip \
          --account-name startifactblob \
          --container-name artifacts \
          --account-key ${{ secrets.AZURE_ACCOUNT_KEY_ARTIFACT }}

    - name: Deploy to Azure
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ vars.TEST_WEBAPP_NAME }}
        publish-profile: ${{ secrets.TEST_BOTFUNC_PUBLISHPROFILE }}
        package: ./publish/${{ vars.AZURE_ARTIFACT_NAME }}-${{ steps.get_version.outputs.version }}.zip

    - name: Log out of Azure
      run: az logout

  ping:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: Get version
        id: get_version
        run: echo "version=$(echo $GITHUB_REF | cut -d / -f 3)" >> $GITHUB_OUTPUT

      - name: Ping Health Check URL
        uses: GarageGroup/platform-ping-app@v0.0.3
        with:
          health_check_url: https://${{ vars.TEST_WEBAPP_NAME }}.azurewebsites.net/health?code=${{ secrets.TEST_BOTFUNC_KEY }}
          contains: ${{ steps.get_version.outputs.version }}
          retry_delay_in_seconds: 15
          max_attempts: 10